coverage:
  precision: 2
  round: down
  range: "50...100"
  notify:
    require_ci_to_pass: yes

  status:
    project: yes

    patch: yes

    changes: yes

  ignore:
    - test_*.py

comment:
  layout: "header, diff, changes"
  behavior: default

